# Generated by Django 5.1.7 on 2025-04-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
