# Generated by Django 5.1.7 on 2025-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_rename_form_contestform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='id',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
