# Generated by Django 5.1.7 on 2025-04-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_remove_contest_id_contest_contest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_id',
        ),
        migrations.AddField(
            model_name='contest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
